name: docs and static analysis

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install package with docs extras
        run: python -m pip install -e ".[docs]"
      - name: Build docs
        run: make -C docs

  static-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install ruff
        run: python -m pip install ruff==0.6.9
      - name: Run formatter and linter
        run: |
          ruff format --check .
          ruff check .
